insert into TO_DO(ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
values (1001,'SMK1','LEARN AWS',CURRENT_DATE(),false);

insert into TO_DO(ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
values (1002,'SMK2','LEARN Azure',CURRENT_DATE(),false);

insert into TO_DO(ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
values (1003,'SMK3','LEARN GCP',CURRENT_DATE(),false);

insert into TO_DO(ID,USER_NAME,DESCRIPTION,TARGET_DATE,DONE)
values (1004,'SMK4','LEARN IBM cloud',CURRENT_DATE(),false);